// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.DataBase.Contexts;

#nullable disable

namespace TaskManagement.DataBase.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240626072456_20240626updateStartData")]
    partial class _20240626updateStartData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.DataBase.Entities.HistoryChangeStatusTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskId");

                    b.ToTable("HistoryChangeStatusTask");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1994, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            TaskId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2017, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            TaskId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(1990, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 4,
                            TaskId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(1984, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 4,
                            TaskId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(1994, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            TaskId = 5
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(1986, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            TaskId = 6
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2009, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 4,
                            TaskId = 7
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(1993, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            TaskId = 8
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(1980, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            TaskId = 9
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2003, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            TaskId = 10
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2003, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            TaskId = 11
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(1985, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            TaskId = 12
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(1976, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            TaskId = 13
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(1978, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            TaskId = 14
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2001, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            TaskId = 15
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(1995, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            TaskId = 16
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(1993, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            TaskId = 17
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(1975, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 4,
                            TaskId = 18
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2000, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            TaskId = 19
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Project#1"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Project#2"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Project#3"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Project#4"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Project#5"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Project#6"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Project#7"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Project#8"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Project#9"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Project#10"
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.ProjectProjectAdministrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectAdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAdministratorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProjectAdministrators");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project Administrator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Worker"
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Открыта"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 3,
                            Name = "На рассмотрении администратором"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Вернута администратором"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Закрыта"
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(8799));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1988, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#1",
                            EndDate = new DateTime(2024, 7, 6, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9808),
                            Name = "Task#1",
                            ProjectId = 6,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9806),
                            UserId = 64
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1975, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#2",
                            EndDate = new DateTime(2024, 7, 3, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9840),
                            Name = "Task#2",
                            ProjectId = 7,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9839),
                            UserId = 59
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2014, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#3",
                            EndDate = new DateTime(2024, 6, 27, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9863),
                            Name = "Task#3",
                            ProjectId = 5,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9862),
                            UserId = 61
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#4",
                            EndDate = new DateTime(2024, 6, 28, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9909),
                            Name = "Task#4",
                            ProjectId = 2,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9909),
                            UserId = 59
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1995, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#5",
                            EndDate = new DateTime(2024, 7, 1, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9933),
                            Name = "Task#5",
                            ProjectId = 4,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9932),
                            UserId = 53
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2000, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#6",
                            EndDate = new DateTime(2024, 6, 28, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9957),
                            Name = "Task#6",
                            ProjectId = 1,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9957),
                            UserId = 66
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1973, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#7",
                            EndDate = new DateTime(2024, 7, 8, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9981),
                            Name = "Task#7",
                            ProjectId = 4,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 519, DateTimeKind.Local).AddTicks(9980),
                            UserId = 52
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2006, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#8",
                            EndDate = new DateTime(2024, 7, 10, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(7),
                            Name = "Task#8",
                            ProjectId = 9,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(7),
                            UserId = 55
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1997, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#9",
                            EndDate = new DateTime(2024, 7, 7, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(30),
                            Name = "Task#9",
                            ProjectId = 1,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(29),
                            UserId = 69
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1998, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#10",
                            EndDate = new DateTime(2024, 7, 4, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(55),
                            Name = "Task#10",
                            ProjectId = 7,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(54),
                            UserId = 58
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2018, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#11",
                            EndDate = new DateTime(2024, 7, 4, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(78),
                            Name = "Task#11",
                            ProjectId = 7,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(77),
                            UserId = 70
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#12",
                            EndDate = new DateTime(2024, 6, 28, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(104),
                            Name = "Task#12",
                            ProjectId = 2,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(103),
                            UserId = 71
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2008, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#13",
                            EndDate = new DateTime(2024, 7, 13, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(128),
                            Name = "Task#13",
                            ProjectId = 1,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(127),
                            UserId = 74
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2013, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#14",
                            EndDate = new DateTime(2024, 6, 27, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(150),
                            Name = "Task#14",
                            ProjectId = 1,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(149),
                            UserId = 66
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1994, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#15",
                            EndDate = new DateTime(2024, 7, 5, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(173),
                            Name = "Task#15",
                            ProjectId = 2,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(173),
                            UserId = 72
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2003, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#16",
                            EndDate = new DateTime(2024, 7, 8, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(199),
                            Name = "Task#16",
                            ProjectId = 3,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(198),
                            UserId = 74
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2008, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#17",
                            EndDate = new DateTime(2024, 7, 2, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(223),
                            Name = "Task#17",
                            ProjectId = 8,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(222),
                            UserId = 65
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(1999, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#18",
                            EndDate = new DateTime(2024, 6, 30, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(248),
                            Name = "Task#18",
                            ProjectId = 6,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(247),
                            UserId = 60
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2009, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description#19",
                            EndDate = new DateTime(2024, 7, 10, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(277),
                            Name = "Task#19",
                            ProjectId = 7,
                            StartDate = new DateTime(2024, 6, 26, 10, 24, 56, 520, DateTimeKind.Local).AddTicks(276),
                            UserId = 55
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Иван",
                            LastName = "Иванов",
                            Login = "log1",
                            Password = "pas1",
                            Patronymic = "Максимович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Максим",
                            LastName = "Буранов",
                            Login = "log2",
                            Password = "pas2",
                            Patronymic = "Максимович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Иван",
                            LastName = "Гримов",
                            Login = "log3",
                            Password = "pas3",
                            Patronymic = "Никитович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Даниил",
                            LastName = "Ивашкин",
                            Login = "log4",
                            Password = "pas4",
                            Patronymic = "Александрович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Юрий",
                            LastName = "Куколович",
                            Login = "log5",
                            Password = "pas5",
                            Patronymic = "Петрович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Алексей",
                            LastName = "Буранов",
                            Login = "log6",
                            Password = "pas6",
                            Patronymic = "Иванович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Максим",
                            LastName = "Александров",
                            Login = "log7",
                            Password = "pas7",
                            Patronymic = "Петрович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Григорий",
                            LastName = "Петров",
                            Login = "log8",
                            Password = "pas8",
                            Patronymic = "Никитович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Григорий",
                            LastName = "Сидоров",
                            Login = "log9",
                            Password = "pas9",
                            Patronymic = "Иванович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Григорий",
                            LastName = "Иванов",
                            Login = "log10",
                            Password = "pas10",
                            Patronymic = "Сергеевич",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Юрий",
                            LastName = "Серлов",
                            Login = "log11",
                            Password = "pas11",
                            Patronymic = "Юрьевич",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Максим",
                            LastName = "Печкин",
                            Login = "log12",
                            Password = "pas12",
                            Patronymic = "Александрович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Сергей",
                            LastName = "Петров",
                            Login = "log13",
                            Password = "pas13",
                            Patronymic = "Даниилович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Петр",
                            LastName = "Сидоров",
                            Login = "log14",
                            Password = "pas14",
                            Patronymic = "Владиславович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Александр",
                            LastName = "Печкин",
                            Login = "log15",
                            Password = "pas15",
                            Patronymic = "Максимович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Алексей",
                            LastName = "Александров",
                            Login = "log16",
                            Password = "pas16",
                            Patronymic = "Даниилович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Петр",
                            LastName = "Куколович",
                            Login = "log17",
                            Password = "pas17",
                            Patronymic = "Юрьевич",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Юрий",
                            LastName = "Сидоров",
                            Login = "log18",
                            Password = "pas18",
                            Patronymic = "Григорьевич",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Максим",
                            LastName = "Ивашкин",
                            Login = "log19",
                            Password = "pas19",
                            Patronymic = "Сергеевич",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Владислав",
                            LastName = "Печкин",
                            Login = "log20",
                            Password = "pas20",
                            Patronymic = "Владиславович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Иван",
                            LastName = "Печкин",
                            Login = "log21",
                            Password = "pas21",
                            Patronymic = "Владиславович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Сергей",
                            LastName = "Иванов",
                            Login = "log22",
                            Password = "pas22",
                            Patronymic = "Сергеевич",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Юрий",
                            LastName = "Петров",
                            Login = "log23",
                            Password = "pas23",
                            Patronymic = "Петрович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Максим",
                            LastName = "Петров",
                            Login = "log24",
                            Password = "pas24",
                            Patronymic = "Иванович",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Иван",
                            LastName = "Александров",
                            Login = "log25",
                            Password = "pas25",
                            Patronymic = "Сергеевич",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Григорий",
                            LastName = "Куколович",
                            Login = "log26",
                            Password = "pas26",
                            Patronymic = "Даниилович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Иван",
                            LastName = "Александров",
                            Login = "log27",
                            Password = "pas27",
                            Patronymic = "Петрович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Владислав",
                            LastName = "Печкин",
                            Login = "log28",
                            Password = "pas28",
                            Patronymic = "Никитович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Даниил",
                            LastName = "Александров",
                            Login = "log29",
                            Password = "pas29",
                            Patronymic = "Александрович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Максим",
                            LastName = "Гримов",
                            Login = "log30",
                            Password = "pas30",
                            Patronymic = "Владиславович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Владислав",
                            LastName = "Сидоров",
                            Login = "log31",
                            Password = "pas31",
                            Patronymic = "Максимович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Сергей",
                            LastName = "Иванов",
                            Login = "log32",
                            Password = "pas32",
                            Patronymic = "Даниилович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Максим",
                            LastName = "Печкин",
                            Login = "log33",
                            Password = "pas33",
                            Patronymic = "Иванович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Иван",
                            LastName = "Петров",
                            Login = "log34",
                            Password = "pas34",
                            Patronymic = "Максимович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Иван",
                            LastName = "Александров",
                            Login = "log35",
                            Password = "pas35",
                            Patronymic = "Иванович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Григорий",
                            LastName = "Харизматов",
                            Login = "log36",
                            Password = "pas36",
                            Patronymic = "Юрьевич",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Владислав",
                            LastName = "Буранов",
                            Login = "log37",
                            Password = "pas37",
                            Patronymic = "Иванович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Юрий",
                            LastName = "Гримов",
                            Login = "log38",
                            Password = "pas38",
                            Patronymic = "Никитович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Петр",
                            LastName = "Буранов",
                            Login = "log39",
                            Password = "pas39",
                            Patronymic = "Петрович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Владислав",
                            LastName = "Иванов",
                            Login = "log40",
                            Password = "pas40",
                            Patronymic = "Петрович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Даниил",
                            LastName = "Куколович",
                            Login = "log41",
                            Password = "pas41",
                            Patronymic = "Никитович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Сергей",
                            LastName = "Харизматов",
                            Login = "log42",
                            Password = "pas42",
                            Patronymic = "Владиславович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Юрий",
                            LastName = "Буранов",
                            Login = "log43",
                            Password = "pas43",
                            Patronymic = "Даниилович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Алексей",
                            LastName = "Харизматов",
                            Login = "log44",
                            Password = "pas44",
                            Patronymic = "Владиславович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Максим",
                            LastName = "Куколович",
                            Login = "log45",
                            Password = "pas45",
                            Patronymic = "Сергеевич",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Григорий",
                            LastName = "Александров",
                            Login = "log46",
                            Password = "pas46",
                            Patronymic = "Сергеевич",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Максим",
                            LastName = "Ивашкин",
                            Login = "log47",
                            Password = "pas47",
                            Patronymic = "Никитович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Владислав",
                            LastName = "Петров",
                            Login = "log48",
                            Password = "pas48",
                            Patronymic = "Максимович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Даниил",
                            LastName = "Петров",
                            Login = "log49",
                            Password = "pas49",
                            Patronymic = "Даниилович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Владислав",
                            LastName = "Куколович",
                            Login = "log50",
                            Password = "pas50",
                            Patronymic = "Владиславович",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Максим",
                            LastName = "Буранов",
                            Login = "log51",
                            Password = "pas51",
                            Patronymic = "Сергеевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Алексей",
                            LastName = "Ивашкин",
                            Login = "log52",
                            Password = "pas52",
                            Patronymic = "Владиславович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Владислав",
                            LastName = "Ивашкин",
                            Login = "log53",
                            Password = "pas53",
                            Patronymic = "Александрович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Александр",
                            LastName = "Александров",
                            Login = "log54",
                            Password = "pas54",
                            Patronymic = "Максимович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Даниил",
                            LastName = "Куколович",
                            Login = "log55",
                            Password = "pas55",
                            Patronymic = "Иванович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Петр",
                            LastName = "Сидоров",
                            Login = "log56",
                            Password = "pas56",
                            Patronymic = "Петрович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Петр",
                            LastName = "Куколович",
                            Login = "log57",
                            Password = "pas57",
                            Patronymic = "Даниилович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Александр",
                            LastName = "Куколович",
                            Login = "log58",
                            Password = "pas58",
                            Patronymic = "Никитович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Александр",
                            LastName = "Харизматов",
                            Login = "log59",
                            Password = "pas59",
                            Patronymic = "Алексеевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Петр",
                            LastName = "Буранов",
                            Login = "log60",
                            Password = "pas60",
                            Patronymic = "Никитович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Владислав",
                            LastName = "Печкин",
                            Login = "log61",
                            Password = "pas61",
                            Patronymic = "Алексеевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Сергей",
                            LastName = "Харизматов",
                            Login = "log62",
                            Password = "pas62",
                            Patronymic = "Максимович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Григорий",
                            LastName = "Куколович",
                            Login = "log63",
                            Password = "pas63",
                            Patronymic = "Сергеевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Даниил",
                            LastName = "Печкин",
                            Login = "log64",
                            Password = "pas64",
                            Patronymic = "Григорьевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Сергей",
                            LastName = "Серлов",
                            Login = "log65",
                            Password = "pas65",
                            Patronymic = "Иванович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Григорий",
                            LastName = "Сидоров",
                            Login = "log66",
                            Password = "pas66",
                            Patronymic = "Григорьевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Петр",
                            LastName = "Буранов",
                            Login = "log67",
                            Password = "pas67",
                            Patronymic = "Максимович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Алексей",
                            LastName = "Гримов",
                            Login = "log68",
                            Password = "pas68",
                            Patronymic = "Даниилович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Владислав",
                            LastName = "Иванов",
                            Login = "log69",
                            Password = "pas69",
                            Patronymic = "Владиславович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Петр",
                            LastName = "Сидоров",
                            Login = "log70",
                            Password = "pas70",
                            Patronymic = "Алексеевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Никита",
                            LastName = "Сидоров",
                            Login = "log71",
                            Password = "pas71",
                            Patronymic = "Юрьевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Юрий",
                            LastName = "Иванов",
                            Login = "log72",
                            Password = "pas72",
                            Patronymic = "Никитович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Максим",
                            LastName = "Серлов",
                            Login = "log73",
                            Password = "pas73",
                            Patronymic = "Юрьевич",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Александр",
                            LastName = "Харизматов",
                            Login = "log74",
                            Password = "pas74",
                            Patronymic = "Даниилович",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Даниил",
                            LastName = "Иванов",
                            Login = "log75",
                            Password = "pas75",
                            Patronymic = "Максимович",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.HistoryChangeStatusTask", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.Status", "Status")
                        .WithMany("HistoryChangeStatusTask")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.DataBase.Entities.Task", "Task")
                        .WithMany("HistoryChangeStatusTask")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.ProjectProjectAdministrator", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.User", "ProjectAdministrator")
                        .WithMany()
                        .HasForeignKey("ProjectAdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.DataBase.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectAdministrator");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Task", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.DataBase.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.User", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Status", b =>
                {
                    b.Navigation("HistoryChangeStatusTask");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Task", b =>
                {
                    b.Navigation("HistoryChangeStatusTask");
                });
#pragma warning restore 612, 618
        }
    }
}
