// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.DataBase.Contexts;

#nullable disable

namespace TaskManagement.DataBase.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.DataBase.Entities.HistoryChangeStatusTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskId");

                    b.ToTable("HistoryChangeStatusTask");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            StatusId = 4,
                            TaskId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            StatusId = 2,
                            TaskId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            StatusId = 4,
                            TaskId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            StatusId = 2,
                            TaskId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            StatusId = 3,
                            TaskId = 5
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Project1"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Project2"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Project3"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Project4"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Project5"
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.ProjectProjectAdministrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectAdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAdministratorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProjectAdministrators");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project Administrator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Worker"
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Открыта"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 3,
                            Name = "На рассмотрении администратором"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Вернута администратором"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Закрыта"
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "desc1",
                            Name = "name1",
                            ProjectId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "desc1",
                            Name = "name1",
                            ProjectId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "desc1",
                            Name = "name1",
                            ProjectId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "desc1",
                            Name = "name1",
                            ProjectId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "desc1",
                            Name = "name1",
                            ProjectId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deadline = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "desc1",
                            Name = "name1",
                            ProjectId = 1,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "FirstName0",
                            LastName = "LastName0",
                            Login = "Login1",
                            Password = "Password1",
                            Patronymic = "Patronymic0",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Login = "Login2",
                            Password = "Password2",
                            Patronymic = "Patronymic1",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Login = "Login3",
                            Password = "Password3",
                            Patronymic = "Patronymic2",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "FirstName3",
                            LastName = "LastName3",
                            Login = "Login4",
                            Password = "Password4",
                            Patronymic = "Patronymic3",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "FirstName4",
                            LastName = "LastName4",
                            Login = "Login5",
                            Password = "Password5",
                            Patronymic = "Patronymic4",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "FirstName5",
                            LastName = "LastName5",
                            Login = "Login6",
                            Password = "Password6",
                            Patronymic = "Patronymic5",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "FirstName6",
                            LastName = "LastName6",
                            Login = "Login7",
                            Password = "Password7",
                            Patronymic = "Patronymic6",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "FirstName7",
                            LastName = "LastName7",
                            Login = "Login8",
                            Password = "Password8",
                            Patronymic = "Patronymic7",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "FirstName8",
                            LastName = "LastName8",
                            Login = "Login9",
                            Password = "Password9",
                            Patronymic = "Patronymic8",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "FirstName9",
                            LastName = "LastName9",
                            Login = "Login10",
                            Password = "Password10",
                            Patronymic = "Patronymic9",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "FirstName10",
                            LastName = "LastName10",
                            Login = "Login11",
                            Password = "Password11",
                            Patronymic = "Patronymic10",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "FirstName11",
                            LastName = "LastName11",
                            Login = "Login12",
                            Password = "Password12",
                            Patronymic = "Patronymic11",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "FirstName12",
                            LastName = "LastName12",
                            Login = "Login13",
                            Password = "Password13",
                            Patronymic = "Patronymic12",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "FirstName13",
                            LastName = "LastName13",
                            Login = "Login14",
                            Password = "Password14",
                            Patronymic = "Patronymic13",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "FirstName14",
                            LastName = "LastName14",
                            Login = "Login15",
                            Password = "Password15",
                            Patronymic = "Patronymic14",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "FirstName15",
                            LastName = "LastName15",
                            Login = "Login16",
                            Password = "Password16",
                            Patronymic = "Patronymic15",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "FirstName16",
                            LastName = "LastName16",
                            Login = "Login17",
                            Password = "Password17",
                            Patronymic = "Patronymic16",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "FirstName17",
                            LastName = "LastName17",
                            Login = "Login18",
                            Password = "Password18",
                            Patronymic = "Patronymic17",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "FirstName18",
                            LastName = "LastName18",
                            Login = "Login19",
                            Password = "Password19",
                            Patronymic = "Patronymic18",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "FirstName19",
                            LastName = "LastName19",
                            Login = "Login20",
                            Password = "Password20",
                            Patronymic = "Patronymic19",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "FirstName20",
                            LastName = "LastName20",
                            Login = "Login21",
                            Password = "Password21",
                            Patronymic = "Patronymic20",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "FirstName21",
                            LastName = "LastName21",
                            Login = "Login22",
                            Password = "Password22",
                            Patronymic = "Patronymic21",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "FirstName22",
                            LastName = "LastName22",
                            Login = "Login23",
                            Password = "Password23",
                            Patronymic = "Patronymic22",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "FirstName23",
                            LastName = "LastName23",
                            Login = "Login24",
                            Password = "Password24",
                            Patronymic = "Patronymic23",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "FirstName24",
                            LastName = "LastName24",
                            Login = "Login25",
                            Password = "Password25",
                            Patronymic = "Patronymic24",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "FirstName0",
                            LastName = "LastName0",
                            Login = "Login26",
                            Password = "Password26",
                            Patronymic = "Patronymic0",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Login = "Login27",
                            Password = "Password27",
                            Patronymic = "Patronymic1",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Login = "Login28",
                            Password = "Password28",
                            Patronymic = "Patronymic2",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "FirstName3",
                            LastName = "LastName3",
                            Login = "Login29",
                            Password = "Password29",
                            Patronymic = "Patronymic3",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "FirstName4",
                            LastName = "LastName4",
                            Login = "Login30",
                            Password = "Password30",
                            Patronymic = "Patronymic4",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "FirstName5",
                            LastName = "LastName5",
                            Login = "Login31",
                            Password = "Password31",
                            Patronymic = "Patronymic5",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "FirstName6",
                            LastName = "LastName6",
                            Login = "Login32",
                            Password = "Password32",
                            Patronymic = "Patronymic6",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "FirstName7",
                            LastName = "LastName7",
                            Login = "Login33",
                            Password = "Password33",
                            Patronymic = "Patronymic7",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "FirstName8",
                            LastName = "LastName8",
                            Login = "Login34",
                            Password = "Password34",
                            Patronymic = "Patronymic8",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "FirstName9",
                            LastName = "LastName9",
                            Login = "Login35",
                            Password = "Password35",
                            Patronymic = "Patronymic9",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "FirstName10",
                            LastName = "LastName10",
                            Login = "Login36",
                            Password = "Password36",
                            Patronymic = "Patronymic10",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "FirstName11",
                            LastName = "LastName11",
                            Login = "Login37",
                            Password = "Password37",
                            Patronymic = "Patronymic11",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "FirstName12",
                            LastName = "LastName12",
                            Login = "Login38",
                            Password = "Password38",
                            Patronymic = "Patronymic12",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "FirstName13",
                            LastName = "LastName13",
                            Login = "Login39",
                            Password = "Password39",
                            Patronymic = "Patronymic13",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "FirstName14",
                            LastName = "LastName14",
                            Login = "Login40",
                            Password = "Password40",
                            Patronymic = "Patronymic14",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "FirstName15",
                            LastName = "LastName15",
                            Login = "Login41",
                            Password = "Password41",
                            Patronymic = "Patronymic15",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "FirstName16",
                            LastName = "LastName16",
                            Login = "Login42",
                            Password = "Password42",
                            Patronymic = "Patronymic16",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "FirstName17",
                            LastName = "LastName17",
                            Login = "Login43",
                            Password = "Password43",
                            Patronymic = "Patronymic17",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "FirstName18",
                            LastName = "LastName18",
                            Login = "Login44",
                            Password = "Password44",
                            Patronymic = "Patronymic18",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "FirstName19",
                            LastName = "LastName19",
                            Login = "Login45",
                            Password = "Password45",
                            Patronymic = "Patronymic19",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "FirstName20",
                            LastName = "LastName20",
                            Login = "Login46",
                            Password = "Password46",
                            Patronymic = "Patronymic20",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "FirstName21",
                            LastName = "LastName21",
                            Login = "Login47",
                            Password = "Password47",
                            Patronymic = "Patronymic21",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "FirstName22",
                            LastName = "LastName22",
                            Login = "Login48",
                            Password = "Password48",
                            Patronymic = "Patronymic22",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "FirstName23",
                            LastName = "LastName23",
                            Login = "Login49",
                            Password = "Password49",
                            Patronymic = "Patronymic23",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "FirstName24",
                            LastName = "LastName24",
                            Login = "Login50",
                            Password = "Password50",
                            Patronymic = "Patronymic24",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "FirstName0",
                            LastName = "LastName0",
                            Login = "Login51",
                            Password = "Password51",
                            Patronymic = "Patronymic0",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Login = "Login52",
                            Password = "Password52",
                            Patronymic = "Patronymic1",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Login = "Login53",
                            Password = "Password53",
                            Patronymic = "Patronymic2",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "FirstName3",
                            LastName = "LastName3",
                            Login = "Login54",
                            Password = "Password54",
                            Patronymic = "Patronymic3",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "FirstName4",
                            LastName = "LastName4",
                            Login = "Login55",
                            Password = "Password55",
                            Patronymic = "Patronymic4",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "FirstName5",
                            LastName = "LastName5",
                            Login = "Login56",
                            Password = "Password56",
                            Patronymic = "Patronymic5",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "FirstName6",
                            LastName = "LastName6",
                            Login = "Login57",
                            Password = "Password57",
                            Patronymic = "Patronymic6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "FirstName7",
                            LastName = "LastName7",
                            Login = "Login58",
                            Password = "Password58",
                            Patronymic = "Patronymic7",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "FirstName8",
                            LastName = "LastName8",
                            Login = "Login59",
                            Password = "Password59",
                            Patronymic = "Patronymic8",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "FirstName9",
                            LastName = "LastName9",
                            Login = "Login60",
                            Password = "Password60",
                            Patronymic = "Patronymic9",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "FirstName10",
                            LastName = "LastName10",
                            Login = "Login61",
                            Password = "Password61",
                            Patronymic = "Patronymic10",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "FirstName11",
                            LastName = "LastName11",
                            Login = "Login62",
                            Password = "Password62",
                            Patronymic = "Patronymic11",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "FirstName12",
                            LastName = "LastName12",
                            Login = "Login63",
                            Password = "Password63",
                            Patronymic = "Patronymic12",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "FirstName13",
                            LastName = "LastName13",
                            Login = "Login64",
                            Password = "Password64",
                            Patronymic = "Patronymic13",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "FirstName14",
                            LastName = "LastName14",
                            Login = "Login65",
                            Password = "Password65",
                            Patronymic = "Patronymic14",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "FirstName15",
                            LastName = "LastName15",
                            Login = "Login66",
                            Password = "Password66",
                            Patronymic = "Patronymic15",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "FirstName16",
                            LastName = "LastName16",
                            Login = "Login67",
                            Password = "Password67",
                            Patronymic = "Patronymic16",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "FirstName17",
                            LastName = "LastName17",
                            Login = "Login68",
                            Password = "Password68",
                            Patronymic = "Patronymic17",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "FirstName18",
                            LastName = "LastName18",
                            Login = "Login69",
                            Password = "Password69",
                            Patronymic = "Patronymic18",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "FirstName19",
                            LastName = "LastName19",
                            Login = "Login70",
                            Password = "Password70",
                            Patronymic = "Patronymic19",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "FirstName20",
                            LastName = "LastName20",
                            Login = "Login71",
                            Password = "Password71",
                            Patronymic = "Patronymic20",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "FirstName21",
                            LastName = "LastName21",
                            Login = "Login72",
                            Password = "Password72",
                            Patronymic = "Patronymic21",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "FirstName22",
                            LastName = "LastName22",
                            Login = "Login73",
                            Password = "Password73",
                            Patronymic = "Patronymic22",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "FirstName23",
                            LastName = "LastName23",
                            Login = "Login74",
                            Password = "Password74",
                            Patronymic = "Patronymic23",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "FirstName24",
                            LastName = "LastName24",
                            Login = "Login75",
                            Password = "Password75",
                            Patronymic = "Patronymic24",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.HistoryChangeStatusTask", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.Status", "Status")
                        .WithMany("HistoryChangeStatusTask")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.DataBase.Entities.Task", "Task")
                        .WithMany("HistoryChangeStatusTask")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.ProjectProjectAdministrator", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.User", "ProjectAdministrator")
                        .WithMany()
                        .HasForeignKey("ProjectAdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.DataBase.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectAdministrator");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Task", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.DataBase.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.User", b =>
                {
                    b.HasOne("TaskManagement.DataBase.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Status", b =>
                {
                    b.Navigation("HistoryChangeStatusTask");
                });

            modelBuilder.Entity("TaskManagement.DataBase.Entities.Task", b =>
                {
                    b.Navigation("HistoryChangeStatusTask");
                });
#pragma warning restore 612, 618
        }
    }
}
